[2024-10-14T02:37:42.836+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/test.py
[2024-10-14T02:37:42.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:37:42.841+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.840+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:37:42.876+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:37:42.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:37:42.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:37:42.904+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2024-10-14T02:38:13.634+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test.py
[2024-10-14T02:38:13.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:38:13.636+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.636+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:38:13.647+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:13.644+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:38:13.648+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:38:13.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:38:44.249+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2024-10-14T02:38:44.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:38:44.252+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:38:44.264+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:38:44.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:38:44.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:38:44.285+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.041 seconds
[2024-10-14T02:39:15.011+0000] {processor.py:186} INFO - Started process (PID=255) to work on /opt/airflow/dags/test.py
[2024-10-14T02:39:15.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:39:15.018+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.017+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:39:15.032+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:15.030+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:39:15.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:39:15.057+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.054 seconds
[2024-10-14T02:39:45.224+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/test.py
[2024-10-14T02:39:45.225+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:39:45.228+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:39:45.249+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:39:45.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:39:45.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:39:45.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-10-14T02:40:15.435+0000] {processor.py:186} INFO - Started process (PID=383) to work on /opt/airflow/dags/test.py
[2024-10-14T02:40:15.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:40:15.438+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:40:15.453+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:15.450+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:40:15.455+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:40:15.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-14T02:40:46.021+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/test.py
[2024-10-14T02:40:46.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:40:46.025+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:40:46.039+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:40:46.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:40:46.041+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:40:46.070+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.054 seconds
[2024-10-14T02:41:16.925+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/test.py
[2024-10-14T02:41:16.926+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:41:16.929+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:41:16.942+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:16.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:41:16.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:41:16.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.044 seconds
[2024-10-14T02:41:47.242+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/test.py
[2024-10-14T02:41:47.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:41:47.248+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:41:47.262+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:41:47.257+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:41:47.263+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:41:47.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:42:17.754+0000] {processor.py:186} INFO - Started process (PID=639) to work on /opt/airflow/dags/test.py
[2024-10-14T02:42:17.755+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:42:17.757+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:42:17.773+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:17.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:42:17.775+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:42:17.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:42:48.503+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/test.py
[2024-10-14T02:42:48.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:42:48.506+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:42:48.521+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:42:48.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:42:48.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:42:48.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-14T02:43:21.409+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/test.py
[2024-10-14T02:43:21.410+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:43:21.413+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.413+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:43:21.430+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:21.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:43:21.431+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:43:21.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-14T02:43:51.648+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/test.py
[2024-10-14T02:43:51.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:43:51.652+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:43:51.671+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:43:51.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:43:51.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:43:51.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-14T02:44:25.045+0000] {processor.py:186} INFO - Started process (PID=840) to work on /opt/airflow/dags/test.py
[2024-10-14T02:44:25.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:44:25.049+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:44:25.066+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:25.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:44:25.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:44:25.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2024-10-14T02:44:57.843+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/test.py
[2024-10-14T02:44:57.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:44:57.848+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:44:57.864+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:44:57.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:44:57.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:44:57.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.052 seconds
[2024-10-14T02:45:30.727+0000] {processor.py:186} INFO - Started process (PID=968) to work on /opt/airflow/dags/test.py
[2024-10-14T02:45:30.728+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:45:30.730+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:45:30.740+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:45:30.738+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:45:30.741+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:45:30.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:46:04.040+0000] {processor.py:186} INFO - Started process (PID=1032) to work on /opt/airflow/dags/test.py
[2024-10-14T02:46:04.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:46:04.044+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:46:04.062+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:04.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:46:04.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:46:04.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2024-10-14T02:46:37.100+0000] {processor.py:186} INFO - Started process (PID=1096) to work on /opt/airflow/dags/test.py
[2024-10-14T02:46:37.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:46:37.103+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:46:37.115+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:46:37.113+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:46:37.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:46:37.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-14T02:47:10.252+0000] {processor.py:186} INFO - Started process (PID=1160) to work on /opt/airflow/dags/test.py
[2024-10-14T02:47:10.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:47:10.255+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.255+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:47:10.267+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:10.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:47:10.268+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:47:10.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-14T02:47:40.668+0000] {processor.py:186} INFO - Started process (PID=1224) to work on /opt/airflow/dags/test.py
[2024-10-14T02:47:40.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:47:40.670+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:47:40.682+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:47:40.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:47:40.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:47:40.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-10-14T02:51:21.664+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/test.py
[2024-10-14T02:51:21.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:51:21.667+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:21.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:51:21.681+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:21.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:51:21.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:51:21.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-14T02:51:51.913+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/test.py
[2024-10-14T02:51:51.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:51:51.918+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:51.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:51:51.930+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:51:51.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:51:51.931+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:51:51.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:52:22.389+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/test.py
[2024-10-14T02:52:22.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:52:22.396+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:22.395+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:52:22.410+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:22.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:52:22.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:52:22.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.053 seconds
[2024-10-14T02:52:52.682+0000] {processor.py:186} INFO - Started process (PID=251) to work on /opt/airflow/dags/test.py
[2024-10-14T02:52:52.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:52:52.685+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:52.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:52:52.695+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:52:52.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:52:52.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:52:52.713+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-14T02:53:23.095+0000] {processor.py:186} INFO - Started process (PID=315) to work on /opt/airflow/dags/test.py
[2024-10-14T02:53:23.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:53:23.098+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:23.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:53:23.108+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:23.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:53:23.110+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:53:23.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:53:53.295+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/test.py
[2024-10-14T02:53:53.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:53:53.298+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:53.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:53:53.310+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:53:53.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:53:53.311+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:53:53.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-14T02:54:23.581+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/test.py
[2024-10-14T02:54:23.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:54:23.586+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:23.585+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:54:23.601+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:23.597+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:54:23.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:54:23.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.053 seconds
[2024-10-14T02:54:54.311+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/test.py
[2024-10-14T02:54:54.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:54:54.315+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:54.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:54:54.330+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:54:54.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:54:54.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:54:54.378+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2024-10-14T02:55:26.701+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/test.py
[2024-10-14T02:55:26.702+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:55:26.704+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:26.703+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:55:26.715+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:26.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:55:26.716+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:55:26.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:55:57.569+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/test.py
[2024-10-14T02:55:57.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:55:57.572+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:57.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:55:57.584+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:55:57.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:55:57.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:55:57.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-14T02:56:28.587+0000] {processor.py:186} INFO - Started process (PID=699) to work on /opt/airflow/dags/test.py
[2024-10-14T02:56:28.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:56:28.591+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:28.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:56:28.601+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:28.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:56:28.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:56:28.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-14T02:56:59.659+0000] {processor.py:186} INFO - Started process (PID=763) to work on /opt/airflow/dags/test.py
[2024-10-14T02:56:59.660+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:56:59.662+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:59.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:56:59.672+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:56:59.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:56:59.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:56:59.690+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T02:57:30.575+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/test.py
[2024-10-14T02:57:30.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:57:30.578+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:57:30.577+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:57:30.589+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:57:30.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:57:30.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:57:30.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.066 seconds
[2024-10-14T02:58:01.338+0000] {processor.py:186} INFO - Started process (PID=885) to work on /opt/airflow/dags/test.py
[2024-10-14T02:58:01.339+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:58:01.341+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:01.341+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:58:01.354+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:01.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:58:01.355+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:58:01.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-14T02:58:32.141+0000] {processor.py:186} INFO - Started process (PID=949) to work on /opt/airflow/dags/test.py
[2024-10-14T02:58:32.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:58:32.144+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:32.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:58:32.159+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:58:32.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:58:32.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:58:32.182+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-14T02:59:02.350+0000] {processor.py:186} INFO - Started process (PID=1013) to work on /opt/airflow/dags/test.py
[2024-10-14T02:59:02.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:59:02.354+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:02.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:59:02.366+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:02.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:59:02.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:59:02.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.153 seconds
[2024-10-14T02:59:32.835+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/test.py
[2024-10-14T02:59:32.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T02:59:32.839+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:32.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T02:59:32.849+0000] {logging_mixin.py:190} INFO - [2024-10-14T02:59:32.847+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T02:59:32.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T02:59:32.868+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-14T03:00:03.770+0000] {processor.py:186} INFO - Started process (PID=1141) to work on /opt/airflow/dags/test.py
[2024-10-14T03:00:03.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:00:03.773+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:03.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:00:03.783+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:03.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:00:03.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:00:03.801+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T03:00:34.686+0000] {processor.py:186} INFO - Started process (PID=1205) to work on /opt/airflow/dags/test.py
[2024-10-14T03:00:34.687+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:00:34.689+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:34.689+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:00:34.700+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:00:34.697+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:00:34.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:00:34.717+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-14T03:01:05.708+0000] {processor.py:186} INFO - Started process (PID=1269) to work on /opt/airflow/dags/test.py
[2024-10-14T03:01:05.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:01:05.711+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:05.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:01:05.722+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:05.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:01:05.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:01:05.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T03:01:36.175+0000] {processor.py:186} INFO - Started process (PID=1333) to work on /opt/airflow/dags/test.py
[2024-10-14T03:01:36.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:01:36.180+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:36.180+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:01:36.202+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:01:36.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:01:36.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:01:36.237+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.071 seconds
[2024-10-14T03:02:08.550+0000] {processor.py:186} INFO - Started process (PID=1390) to work on /opt/airflow/dags/test.py
[2024-10-14T03:02:08.551+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:02:08.554+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:02:08.553+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:02:08.567+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:02:08.564+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:02:08.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:02:08.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.044 seconds
[2024-10-14T03:23:32.304+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/test.py
[2024-10-14T03:23:32.306+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:23:32.310+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:23:32.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:23:32.325+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:23:32.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:23:32.326+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:23:32.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.104 seconds
[2024-10-14T03:24:02.535+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/test.py
[2024-10-14T03:24:02.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:24:02.538+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:02.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:24:02.548+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:02.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:24:02.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:24:02.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-14T03:24:32.804+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2024-10-14T03:24:32.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:24:32.808+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:32.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:24:32.823+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:24:32.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:24:32.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:24:32.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.052 seconds
[2024-10-14T03:25:03.678+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/test.py
[2024-10-14T03:25:03.679+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:25:03.681+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:03.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:25:03.693+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:03.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:25:03.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:25:03.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-10-14T03:25:34.477+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/test.py
[2024-10-14T03:25:34.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:25:34.481+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:34.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:25:34.492+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:25:34.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:25:34.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:25:34.512+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-14T03:26:05.270+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/test.py
[2024-10-14T03:26:05.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:26:05.274+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:05.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:26:05.290+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:05.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:26:05.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:26:05.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-14T03:26:36.080+0000] {processor.py:186} INFO - Started process (PID=447) to work on /opt/airflow/dags/test.py
[2024-10-14T03:26:36.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:26:36.085+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:36.085+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:26:36.115+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:26:36.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:26:36.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:26:36.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2024-10-14T03:27:06.369+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/test.py
[2024-10-14T03:27:06.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:27:06.374+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:06.373+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:27:06.393+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:27:06.388+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:27:06.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:27:06.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.053 seconds
[2024-10-14T03:28:38.561+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/test.py
[2024-10-14T03:28:38.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:28:38.566+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:28:38.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:28:38.585+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:28:38.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:28:38.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:28:38.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.055 seconds
[2024-10-14T03:29:09.260+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/test.py
[2024-10-14T03:29:09.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:29:09.264+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:09.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:29:09.277+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:09.274+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:29:09.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:29:09.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.048 seconds
[2024-10-14T03:29:41.033+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/test.py
[2024-10-14T03:29:41.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-14T03:29:41.037+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:41.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-14T03:29:41.049+0000] {logging_mixin.py:190} INFO - [2024-10-14T03:29:41.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-14T03:29:41.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-14T03:29:41.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.043 seconds
