[2024-10-26T17:19:18.437+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/test.py
[2024-10-26T17:19:18.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:19:18.460+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:19:18.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:19:18.571+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:19:18.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:19:18.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:19:18.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.459 seconds
[2024-10-26T17:19:49.096+0000] {processor.py:186} INFO - Started process (PID=129) to work on /opt/airflow/dags/test.py
[2024-10-26T17:19:49.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:19:49.099+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:19:49.098+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:19:49.149+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:19:49.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:19:49.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:19:49.175+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.086 seconds
[2024-10-26T17:20:19.697+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/test.py
[2024-10-26T17:20:19.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:20:19.721+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:20:19.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:20:19.768+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:20:19.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:20:19.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:20:19.835+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.162 seconds
[2024-10-26T17:20:50.278+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/test.py
[2024-10-26T17:20:50.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:20:50.286+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:20:50.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:20:50.418+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:20:50.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:20:50.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:20:50.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.176 seconds
[2024-10-26T17:21:20.862+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/test.py
[2024-10-26T17:21:20.863+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:21:20.865+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:21:20.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:21:20.878+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:21:20.875+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:21:20.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:21:20.906+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-26T17:21:51.740+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/test.py
[2024-10-26T17:21:51.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:21:51.744+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:21:51.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:21:51.755+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:21:51.752+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:21:51.756+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:21:51.774+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T17:22:22.708+0000] {processor.py:186} INFO - Started process (PID=450) to work on /opt/airflow/dags/test.py
[2024-10-26T17:22:22.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:22:22.712+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:22:22.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:22:22.725+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:22:22.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:22:22.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:22:22.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-26T17:22:52.828+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/test.py
[2024-10-26T17:22:52.829+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:22:52.832+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:22:52.831+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:22:52.844+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:22:52.842+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:22:52.845+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:22:52.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.041 seconds
[2024-10-26T17:23:23.561+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/test.py
[2024-10-26T17:23:23.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:23:23.568+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:23:23.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:23:23.589+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:23:23.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:23:23.591+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:23:23.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.289 seconds
[2024-10-26T17:23:53.941+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/test.py
[2024-10-26T17:23:53.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:23:53.945+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:23:53.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:23:53.958+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:23:53.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:23:53.959+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:23:53.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.046 seconds
[2024-10-26T17:24:24.443+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/test.py
[2024-10-26T17:24:24.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:24:24.449+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:24:24.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:24:24.494+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:24:24.485+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:24:24.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:24:24.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.093 seconds
[2024-10-26T17:24:56.907+0000] {processor.py:186} INFO - Started process (PID=765) to work on /opt/airflow/dags/test.py
[2024-10-26T17:24:56.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:24:56.912+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:24:56.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:24:56.945+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:24:56.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:24:56.948+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:24:56.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.073 seconds
[2024-10-26T17:25:29.785+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/test.py
[2024-10-26T17:25:29.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:25:29.790+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:25:29.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:25:29.823+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:25:29.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:25:29.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:25:29.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.073 seconds
[2024-10-26T17:26:02.456+0000] {processor.py:186} INFO - Started process (PID=893) to work on /opt/airflow/dags/test.py
[2024-10-26T17:26:02.457+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:26:02.461+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:26:02.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:26:02.498+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:26:02.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:26:02.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:26:02.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2024-10-26T17:26:34.606+0000] {processor.py:186} INFO - Started process (PID=958) to work on /opt/airflow/dags/test.py
[2024-10-26T17:26:34.609+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:26:34.613+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:26:34.612+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:26:34.636+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:26:34.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:26:34.638+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:26:34.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.068 seconds
[2024-10-26T17:27:07.502+0000] {processor.py:186} INFO - Started process (PID=1022) to work on /opt/airflow/dags/test.py
[2024-10-26T17:27:07.503+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:27:07.508+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:27:07.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:27:07.541+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:27:07.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:27:07.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:27:07.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2024-10-26T17:27:39.932+0000] {processor.py:186} INFO - Started process (PID=1086) to work on /opt/airflow/dags/test.py
[2024-10-26T17:27:39.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:27:39.943+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:27:39.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:27:39.972+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:27:39.967+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:27:39.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:27:40.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.097 seconds
[2024-10-26T17:28:12.611+0000] {processor.py:186} INFO - Started process (PID=1150) to work on /opt/airflow/dags/test.py
[2024-10-26T17:28:12.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:28:12.616+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:28:12.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:28:12.645+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:28:12.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:28:12.647+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:28:12.668+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.062 seconds
[2024-10-26T17:28:45.299+0000] {processor.py:186} INFO - Started process (PID=1215) to work on /opt/airflow/dags/test.py
[2024-10-26T17:28:45.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:28:45.304+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:28:45.303+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:28:45.329+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:28:45.324+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:28:45.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:28:45.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.064 seconds
[2024-10-26T17:29:18.197+0000] {processor.py:186} INFO - Started process (PID=1279) to work on /opt/airflow/dags/test.py
[2024-10-26T17:29:18.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:29:18.202+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:29:18.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:29:18.237+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:29:18.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:29:18.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:29:18.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.080 seconds
[2024-10-26T17:29:51.090+0000] {processor.py:186} INFO - Started process (PID=1343) to work on /opt/airflow/dags/test.py
[2024-10-26T17:29:51.094+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:29:51.097+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:29:51.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:29:51.128+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:29:51.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:29:51.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:29:51.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.070 seconds
[2024-10-26T17:30:23.942+0000] {processor.py:186} INFO - Started process (PID=1407) to work on /opt/airflow/dags/test.py
[2024-10-26T17:30:23.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:30:23.946+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:30:23.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:30:23.972+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:30:23.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:30:23.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:30:24.041+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.106 seconds
[2024-10-26T17:30:56.426+0000] {processor.py:186} INFO - Started process (PID=1471) to work on /opt/airflow/dags/test.py
[2024-10-26T17:30:56.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:30:56.434+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:30:56.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:30:56.473+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:30:56.464+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:30:56.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:30:56.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.100 seconds
[2024-10-26T17:31:29.251+0000] {processor.py:186} INFO - Started process (PID=1535) to work on /opt/airflow/dags/test.py
[2024-10-26T17:31:29.253+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:31:29.256+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:31:29.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:31:29.289+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:31:29.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:31:29.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:31:29.318+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.074 seconds
[2024-10-26T17:32:01.196+0000] {processor.py:186} INFO - Started process (PID=1599) to work on /opt/airflow/dags/test.py
[2024-10-26T17:32:01.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:32:01.200+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:32:01.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:32:01.234+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:32:01.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:32:01.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:32:01.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.080 seconds
[2024-10-26T17:32:34.022+0000] {processor.py:186} INFO - Started process (PID=1663) to work on /opt/airflow/dags/test.py
[2024-10-26T17:32:34.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:32:34.026+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:32:34.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:32:34.053+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:32:34.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:32:34.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:32:34.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-10-26T17:33:07.280+0000] {processor.py:186} INFO - Started process (PID=1727) to work on /opt/airflow/dags/test.py
[2024-10-26T17:33:07.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:33:07.283+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:33:07.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:33:07.307+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:33:07.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:33:07.309+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:33:07.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.058 seconds
[2024-10-26T17:33:39.489+0000] {processor.py:186} INFO - Started process (PID=1791) to work on /opt/airflow/dags/test.py
[2024-10-26T17:33:39.491+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:33:39.497+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:33:39.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:33:39.529+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:33:39.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:33:39.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:33:39.562+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.081 seconds
[2024-10-26T17:34:12.214+0000] {processor.py:186} INFO - Started process (PID=1855) to work on /opt/airflow/dags/test.py
[2024-10-26T17:34:12.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:34:12.219+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:34:12.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:34:12.261+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:34:12.252+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:34:12.265+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:34:12.300+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.096 seconds
[2024-10-26T17:34:44.773+0000] {processor.py:186} INFO - Started process (PID=1919) to work on /opt/airflow/dags/test.py
[2024-10-26T17:34:44.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:34:44.779+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:34:44.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:34:44.803+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:34:44.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:34:44.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:34:44.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-10-26T17:35:17.902+0000] {processor.py:186} INFO - Started process (PID=1983) to work on /opt/airflow/dags/test.py
[2024-10-26T17:35:17.913+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:35:17.924+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:35:17.923+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:35:17.954+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:35:17.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:35:17.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:35:17.990+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.136 seconds
[2024-10-26T17:35:50.921+0000] {processor.py:186} INFO - Started process (PID=2048) to work on /opt/airflow/dags/test.py
[2024-10-26T17:35:50.925+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:35:50.932+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:35:50.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:35:50.962+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:35:50.955+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:35:50.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:35:50.988+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2024-10-26T17:36:23.638+0000] {processor.py:186} INFO - Started process (PID=2112) to work on /opt/airflow/dags/test.py
[2024-10-26T17:36:23.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:36:23.643+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:36:23.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:36:23.678+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:36:23.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:36:23.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:36:23.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2024-10-26T17:36:55.872+0000] {processor.py:186} INFO - Started process (PID=2176) to work on /opt/airflow/dags/test.py
[2024-10-26T17:36:55.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:36:55.876+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:36:55.876+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:36:55.902+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:36:55.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:36:55.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:36:55.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-10-26T17:37:28.530+0000] {processor.py:186} INFO - Started process (PID=2240) to work on /opt/airflow/dags/test.py
[2024-10-26T17:37:28.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:37:28.534+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:37:28.534+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:37:28.566+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:37:28.558+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:37:28.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:37:28.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.071 seconds
[2024-10-26T17:38:01.214+0000] {processor.py:186} INFO - Started process (PID=2304) to work on /opt/airflow/dags/test.py
[2024-10-26T17:38:01.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:38:01.218+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:38:01.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:38:01.245+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:38:01.239+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:38:01.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:38:01.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.066 seconds
[2024-10-26T17:38:34.465+0000] {processor.py:186} INFO - Started process (PID=2368) to work on /opt/airflow/dags/test.py
[2024-10-26T17:38:34.466+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:38:34.469+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:38:34.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:38:34.495+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:38:34.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:38:34.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:38:34.517+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.060 seconds
[2024-10-26T17:39:07.349+0000] {processor.py:186} INFO - Started process (PID=2432) to work on /opt/airflow/dags/test.py
[2024-10-26T17:39:07.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:39:07.353+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:39:07.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:39:07.380+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:39:07.374+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:39:07.382+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:39:07.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-10-26T17:39:40.086+0000] {processor.py:186} INFO - Started process (PID=2496) to work on /opt/airflow/dags/test.py
[2024-10-26T17:39:40.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:39:40.090+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:39:40.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:39:40.119+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:39:40.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:39:40.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:39:40.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2024-10-26T17:40:12.174+0000] {processor.py:186} INFO - Started process (PID=2560) to work on /opt/airflow/dags/test.py
[2024-10-26T17:40:12.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:40:12.179+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:40:12.178+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:40:12.208+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:40:12.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:40:12.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:40:12.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.072 seconds
[2024-10-26T17:40:44.837+0000] {processor.py:186} INFO - Started process (PID=2624) to work on /opt/airflow/dags/test.py
[2024-10-26T17:40:44.839+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:40:44.845+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:40:44.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:40:44.899+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:40:44.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:40:44.903+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:40:44.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.122 seconds
[2024-10-26T17:41:17.860+0000] {processor.py:186} INFO - Started process (PID=2688) to work on /opt/airflow/dags/test.py
[2024-10-26T17:41:17.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:41:17.864+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:41:17.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:41:17.901+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:41:17.892+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:41:17.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:41:17.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.074 seconds
[2024-10-26T17:41:50.711+0000] {processor.py:186} INFO - Started process (PID=2752) to work on /opt/airflow/dags/test.py
[2024-10-26T17:41:50.712+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:41:50.715+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:41:50.715+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:41:50.742+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:41:50.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:41:50.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:41:50.768+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-10-26T17:42:23.809+0000] {processor.py:186} INFO - Started process (PID=2816) to work on /opt/airflow/dags/test.py
[2024-10-26T17:42:23.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:42:23.814+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:42:23.813+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:42:23.848+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:42:23.839+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:42:23.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:42:23.878+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.077 seconds
[2024-10-26T17:42:55.762+0000] {processor.py:186} INFO - Started process (PID=2880) to work on /opt/airflow/dags/test.py
[2024-10-26T17:42:55.764+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:42:55.768+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:42:55.767+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:42:55.792+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:42:55.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:42:55.793+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:42:55.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-10-26T17:43:28.403+0000] {processor.py:186} INFO - Started process (PID=2944) to work on /opt/airflow/dags/test.py
[2024-10-26T17:43:28.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:43:28.408+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:43:28.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:43:28.441+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:43:28.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:43:28.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:43:28.469+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.075 seconds
[2024-10-26T17:44:01.124+0000] {processor.py:186} INFO - Started process (PID=3008) to work on /opt/airflow/dags/test.py
[2024-10-26T17:44:01.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:44:01.132+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:44:01.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:44:01.157+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:44:01.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:44:01.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:44:01.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.069 seconds
[2024-10-26T17:44:34.335+0000] {processor.py:186} INFO - Started process (PID=3073) to work on /opt/airflow/dags/test.py
[2024-10-26T17:44:34.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:44:34.340+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:44:34.339+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:44:34.375+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:44:34.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:44:34.378+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:44:34.405+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-10-26T17:45:07.381+0000] {processor.py:186} INFO - Started process (PID=3137) to work on /opt/airflow/dags/test.py
[2024-10-26T17:45:07.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:45:07.386+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:45:07.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:45:07.409+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:45:07.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:45:07.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:45:07.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.066 seconds
[2024-10-26T17:45:40.309+0000] {processor.py:186} INFO - Started process (PID=3201) to work on /opt/airflow/dags/test.py
[2024-10-26T17:45:40.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:45:40.312+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:45:40.312+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:45:40.334+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:45:40.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:45:40.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:45:40.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.054 seconds
[2024-10-26T17:46:12.802+0000] {processor.py:186} INFO - Started process (PID=3265) to work on /opt/airflow/dags/test.py
[2024-10-26T17:46:12.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:46:12.807+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:46:12.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:46:12.837+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:46:12.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:46:12.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:46:12.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.069 seconds
[2024-10-26T17:46:45.029+0000] {processor.py:186} INFO - Started process (PID=3329) to work on /opt/airflow/dags/test.py
[2024-10-26T17:46:45.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:46:45.033+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:46:45.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:46:45.055+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:46:45.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:46:45.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:46:45.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.061 seconds
[2024-10-26T17:47:17.782+0000] {processor.py:186} INFO - Started process (PID=3393) to work on /opt/airflow/dags/test.py
[2024-10-26T17:47:17.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:47:17.789+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:47:17.789+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:47:17.823+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:47:17.814+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:47:17.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:47:17.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.079 seconds
[2024-10-26T17:47:50.810+0000] {processor.py:186} INFO - Started process (PID=3457) to work on /opt/airflow/dags/test.py
[2024-10-26T17:47:50.812+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:47:50.815+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:47:50.814+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:47:50.852+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:47:50.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:47:50.854+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:47:50.879+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.076 seconds
[2024-10-26T17:48:23.864+0000] {processor.py:186} INFO - Started process (PID=3521) to work on /opt/airflow/dags/test.py
[2024-10-26T17:48:23.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:48:23.868+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:48:23.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:48:23.895+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:48:23.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:48:23.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:48:23.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.064 seconds
[2024-10-26T17:48:55.964+0000] {processor.py:186} INFO - Started process (PID=3585) to work on /opt/airflow/dags/test.py
[2024-10-26T17:48:55.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:48:55.969+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:48:55.968+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:48:55.994+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:48:55.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:48:55.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:48:56.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.063 seconds
[2024-10-26T17:49:29.349+0000] {processor.py:186} INFO - Started process (PID=3649) to work on /opt/airflow/dags/test.py
[2024-10-26T17:49:29.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:49:29.354+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:49:29.353+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:49:29.385+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:49:29.377+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:49:29.387+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:49:29.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.070 seconds
[2024-10-26T17:50:01.818+0000] {processor.py:186} INFO - Started process (PID=3713) to work on /opt/airflow/dags/test.py
[2024-10-26T17:50:01.820+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:50:01.824+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:50:01.824+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:50:01.874+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:50:01.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:50:01.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:50:01.913+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.103 seconds
[2024-10-26T17:50:34.682+0000] {processor.py:186} INFO - Started process (PID=3777) to work on /opt/airflow/dags/test.py
[2024-10-26T17:50:34.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:50:34.687+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:50:34.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:50:34.716+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:50:34.711+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:50:34.720+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:50:34.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.081 seconds
[2024-10-26T17:51:07.265+0000] {processor.py:186} INFO - Started process (PID=3841) to work on /opt/airflow/dags/test.py
[2024-10-26T17:51:07.267+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:51:07.271+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:51:07.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:51:07.300+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:51:07.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:51:07.302+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:51:07.335+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.081 seconds
[2024-10-26T17:51:39.773+0000] {processor.py:186} INFO - Started process (PID=3905) to work on /opt/airflow/dags/test.py
[2024-10-26T17:51:39.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:51:39.777+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:51:39.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:51:39.804+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:51:39.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:51:39.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:51:39.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.080 seconds
[2024-10-26T17:52:12.734+0000] {processor.py:186} INFO - Started process (PID=3969) to work on /opt/airflow/dags/test.py
[2024-10-26T17:52:12.735+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:52:12.739+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:52:12.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:52:12.765+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:52:12.759+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:52:12.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:52:12.792+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-10-26T17:52:45.025+0000] {processor.py:186} INFO - Started process (PID=4034) to work on /opt/airflow/dags/test.py
[2024-10-26T17:52:45.027+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:52:45.030+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:52:45.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:52:45.055+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:52:45.048+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:52:45.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:52:45.083+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.066 seconds
[2024-10-26T17:53:18.132+0000] {processor.py:186} INFO - Started process (PID=4098) to work on /opt/airflow/dags/test.py
[2024-10-26T17:53:18.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:53:18.137+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:53:18.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:53:18.160+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:53:18.155+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:53:18.162+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:53:18.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.062 seconds
[2024-10-26T17:53:50.937+0000] {processor.py:186} INFO - Started process (PID=4162) to work on /opt/airflow/dags/test.py
[2024-10-26T17:53:50.939+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:53:50.943+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:53:50.942+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:53:50.965+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:53:50.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:53:50.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:53:50.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.060 seconds
[2024-10-26T17:54:24.151+0000] {processor.py:186} INFO - Started process (PID=4226) to work on /opt/airflow/dags/test.py
[2024-10-26T17:54:24.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:54:24.157+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:54:24.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:54:24.183+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:54:24.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:54:24.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:54:24.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.069 seconds
[2024-10-26T17:54:56.190+0000] {processor.py:186} INFO - Started process (PID=4290) to work on /opt/airflow/dags/test.py
[2024-10-26T17:54:56.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:54:56.194+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:54:56.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:54:56.226+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:54:56.218+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:54:56.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:54:56.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.072 seconds
[2024-10-26T17:55:29.316+0000] {processor.py:186} INFO - Started process (PID=4354) to work on /opt/airflow/dags/test.py
[2024-10-26T17:55:29.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:55:29.320+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:55:29.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:55:29.330+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:55:29.327+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:55:29.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:55:29.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T17:56:02.209+0000] {processor.py:186} INFO - Started process (PID=4418) to work on /opt/airflow/dags/test.py
[2024-10-26T17:56:02.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:56:02.215+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:56:02.214+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:56:02.227+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:56:02.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:56:02.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:56:02.245+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-26T17:56:34.163+0000] {processor.py:186} INFO - Started process (PID=4482) to work on /opt/airflow/dags/test.py
[2024-10-26T17:56:34.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:56:34.166+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:56:34.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:56:34.177+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:56:34.174+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:56:34.177+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:56:34.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-10-26T17:57:06.840+0000] {processor.py:186} INFO - Started process (PID=4546) to work on /opt/airflow/dags/test.py
[2024-10-26T17:57:06.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:57:06.844+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:57:06.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:57:06.856+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:57:06.853+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:57:06.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:57:06.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.041 seconds
[2024-10-26T17:57:39.842+0000] {processor.py:186} INFO - Started process (PID=4610) to work on /opt/airflow/dags/test.py
[2024-10-26T17:57:39.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:57:39.849+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:57:39.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:57:39.869+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:57:39.864+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:57:39.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:57:39.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.061 seconds
[2024-10-26T17:58:12.928+0000] {processor.py:186} INFO - Started process (PID=4674) to work on /opt/airflow/dags/test.py
[2024-10-26T17:58:12.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:58:12.932+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:58:12.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:58:12.943+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:58:12.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:58:12.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:58:12.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T17:58:45.513+0000] {processor.py:186} INFO - Started process (PID=4738) to work on /opt/airflow/dags/test.py
[2024-10-26T17:58:45.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:58:45.517+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:58:45.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:58:45.532+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:58:45.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:58:45.533+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:58:45.552+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-26T17:59:18.495+0000] {processor.py:186} INFO - Started process (PID=4802) to work on /opt/airflow/dags/test.py
[2024-10-26T17:59:18.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:59:18.497+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:59:18.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:59:18.509+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:59:18.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:59:18.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:59:18.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T17:59:51.243+0000] {processor.py:186} INFO - Started process (PID=4866) to work on /opt/airflow/dags/test.py
[2024-10-26T17:59:51.244+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T17:59:51.246+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:59:51.246+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T17:59:51.259+0000] {logging_mixin.py:190} INFO - [2024-10-26T17:59:51.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T17:59:51.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T17:59:51.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:00:23.706+0000] {processor.py:186} INFO - Started process (PID=4930) to work on /opt/airflow/dags/test.py
[2024-10-26T18:00:23.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:00:23.714+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:00:23.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:00:23.729+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:00:23.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:00:23.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:00:23.752+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.052 seconds
[2024-10-26T18:00:56.750+0000] {processor.py:186} INFO - Started process (PID=4994) to work on /opt/airflow/dags/test.py
[2024-10-26T18:00:56.752+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:00:56.754+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:00:56.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:00:56.771+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:00:56.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:00:56.773+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:00:56.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.048 seconds
[2024-10-26T18:01:29.066+0000] {processor.py:186} INFO - Started process (PID=5058) to work on /opt/airflow/dags/test.py
[2024-10-26T18:01:29.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:01:29.069+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:01:29.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:01:29.081+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:01:29.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:01:29.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:01:29.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:02:02.039+0000] {processor.py:186} INFO - Started process (PID=5123) to work on /opt/airflow/dags/test.py
[2024-10-26T18:02:02.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:02:02.043+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:02:02.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:02:02.062+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:02:02.057+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:02:02.064+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:02:02.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.064 seconds
[2024-10-26T18:02:34.043+0000] {processor.py:186} INFO - Started process (PID=5187) to work on /opt/airflow/dags/test.py
[2024-10-26T18:02:34.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:02:34.047+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:02:34.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:02:34.065+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:02:34.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:02:34.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:02:34.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.053 seconds
[2024-10-26T18:03:07.360+0000] {processor.py:186} INFO - Started process (PID=5251) to work on /opt/airflow/dags/test.py
[2024-10-26T18:03:07.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:03:07.368+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:03:07.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:03:07.390+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:03:07.385+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:03:07.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:03:07.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.067 seconds
[2024-10-26T18:03:39.644+0000] {processor.py:186} INFO - Started process (PID=5315) to work on /opt/airflow/dags/test.py
[2024-10-26T18:03:39.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:03:39.648+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:03:39.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:03:39.704+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:03:39.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:03:39.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:03:39.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.086 seconds
[2024-10-26T18:04:12.354+0000] {processor.py:186} INFO - Started process (PID=5379) to work on /opt/airflow/dags/test.py
[2024-10-26T18:04:12.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:04:12.357+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:04:12.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:04:12.369+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:04:12.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:04:12.370+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:04:12.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-10-26T18:04:45.035+0000] {processor.py:186} INFO - Started process (PID=5443) to work on /opt/airflow/dags/test.py
[2024-10-26T18:04:45.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:04:45.038+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:04:45.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:04:45.049+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:04:45.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:04:45.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:04:45.068+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-10-26T18:05:17.884+0000] {processor.py:186} INFO - Started process (PID=5507) to work on /opt/airflow/dags/test.py
[2024-10-26T18:05:17.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:05:17.889+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:05:17.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:05:17.901+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:05:17.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:05:17.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:05:17.926+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-26T18:05:50.748+0000] {processor.py:186} INFO - Started process (PID=5571) to work on /opt/airflow/dags/test.py
[2024-10-26T18:05:50.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:05:50.752+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:05:50.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:05:50.767+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:05:50.764+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:05:50.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:05:50.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.048 seconds
[2024-10-26T18:06:24.023+0000] {processor.py:186} INFO - Started process (PID=5635) to work on /opt/airflow/dags/test.py
[2024-10-26T18:06:24.025+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:06:24.031+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:06:24.030+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:06:24.056+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:06:24.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:06:24.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:06:24.095+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.084 seconds
[2024-10-26T18:06:56.789+0000] {processor.py:186} INFO - Started process (PID=5699) to work on /opt/airflow/dags/test.py
[2024-10-26T18:06:56.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:06:56.793+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:06:56.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:06:56.803+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:06:56.801+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:06:56.805+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:06:56.822+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:07:29.313+0000] {processor.py:186} INFO - Started process (PID=5763) to work on /opt/airflow/dags/test.py
[2024-10-26T18:07:29.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:07:29.317+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:07:29.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:07:29.328+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:07:29.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:07:29.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:07:29.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:08:02.151+0000] {processor.py:186} INFO - Started process (PID=5827) to work on /opt/airflow/dags/test.py
[2024-10-26T18:08:02.152+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:08:02.157+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:08:02.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:08:02.173+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:08:02.167+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:08:02.174+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:08:02.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.048 seconds
[2024-10-26T18:08:34.537+0000] {processor.py:186} INFO - Started process (PID=5891) to work on /opt/airflow/dags/test.py
[2024-10-26T18:08:34.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:08:34.541+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:08:34.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:08:34.555+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:08:34.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:08:34.557+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:08:34.577+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-26T18:09:07.334+0000] {processor.py:186} INFO - Started process (PID=5955) to work on /opt/airflow/dags/test.py
[2024-10-26T18:09:07.335+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:09:07.338+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:09:07.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:09:07.352+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:09:07.348+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:09:07.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:09:07.375+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.051 seconds
[2024-10-26T18:09:40.096+0000] {processor.py:186} INFO - Started process (PID=6019) to work on /opt/airflow/dags/test.py
[2024-10-26T18:09:40.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:09:40.100+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:09:40.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:09:40.112+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:09:40.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:09:40.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:09:40.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:10:12.233+0000] {processor.py:186} INFO - Started process (PID=6083) to work on /opt/airflow/dags/test.py
[2024-10-26T18:10:12.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:10:12.236+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:10:12.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:10:12.247+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:10:12.244+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:10:12.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:10:12.265+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:10:44.968+0000] {processor.py:186} INFO - Started process (PID=6147) to work on /opt/airflow/dags/test.py
[2024-10-26T18:10:44.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:10:44.973+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:10:44.972+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:10:44.983+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:10:44.981+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:10:44.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:10:45.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-26T18:11:17.877+0000] {processor.py:186} INFO - Started process (PID=6211) to work on /opt/airflow/dags/test.py
[2024-10-26T18:11:17.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:11:17.881+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:11:17.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:11:17.892+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:11:17.890+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:11:17.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:11:17.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.039 seconds
[2024-10-26T18:11:51.052+0000] {processor.py:186} INFO - Started process (PID=6275) to work on /opt/airflow/dags/test.py
[2024-10-26T18:11:51.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:11:51.057+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:11:51.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:11:51.078+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:11:51.074+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:11:51.081+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:11:51.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.065 seconds
[2024-10-26T18:12:23.139+0000] {processor.py:186} INFO - Started process (PID=6339) to work on /opt/airflow/dags/test.py
[2024-10-26T18:12:23.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:12:23.142+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:12:23.142+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:12:23.159+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:12:23.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:12:23.160+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:12:23.181+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-26T18:12:56.145+0000] {processor.py:186} INFO - Started process (PID=6403) to work on /opt/airflow/dags/test.py
[2024-10-26T18:12:56.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:12:56.148+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:12:56.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:12:56.162+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:12:56.157+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:12:56.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:12:56.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.047 seconds
[2024-10-26T18:13:29.179+0000] {processor.py:186} INFO - Started process (PID=6467) to work on /opt/airflow/dags/test.py
[2024-10-26T18:13:29.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:13:29.184+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:13:29.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:13:29.196+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:13:29.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:13:29.197+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:13:29.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-26T18:14:02.256+0000] {processor.py:186} INFO - Started process (PID=6531) to work on /opt/airflow/dags/test.py
[2024-10-26T18:14:02.257+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:14:02.259+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:14:02.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:14:02.270+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:14:02.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:14:02.271+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:14:02.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:14:34.067+0000] {processor.py:186} INFO - Started process (PID=6595) to work on /opt/airflow/dags/test.py
[2024-10-26T18:14:34.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:14:34.070+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:14:34.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:14:34.082+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:14:34.079+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:14:34.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:14:34.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-10-26T18:15:06.935+0000] {processor.py:186} INFO - Started process (PID=6659) to work on /opt/airflow/dags/test.py
[2024-10-26T18:15:06.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:15:06.938+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:15:06.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:15:06.952+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:15:06.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:15:06.953+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:15:06.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-26T18:15:39.612+0000] {processor.py:186} INFO - Started process (PID=6723) to work on /opt/airflow/dags/test.py
[2024-10-26T18:15:39.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:15:39.616+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:15:39.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:15:39.629+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:15:39.626+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:15:39.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:15:39.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-26T18:16:12.516+0000] {processor.py:186} INFO - Started process (PID=6787) to work on /opt/airflow/dags/test.py
[2024-10-26T18:16:12.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:16:12.519+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:16:12.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:16:12.532+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:16:12.529+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:16:12.534+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:16:12.550+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:16:45.359+0000] {processor.py:186} INFO - Started process (PID=6851) to work on /opt/airflow/dags/test.py
[2024-10-26T18:16:45.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:16:45.364+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:16:45.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:16:45.399+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:16:45.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:16:45.409+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:16:45.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.087 seconds
[2024-10-26T18:17:18.396+0000] {processor.py:186} INFO - Started process (PID=6915) to work on /opt/airflow/dags/test.py
[2024-10-26T18:17:18.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:17:18.402+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:17:18.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:17:18.418+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:17:18.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:17:18.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:17:18.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-26T18:17:50.629+0000] {processor.py:186} INFO - Started process (PID=6979) to work on /opt/airflow/dags/test.py
[2024-10-26T18:17:50.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:17:50.632+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:17:50.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:17:50.643+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:17:50.641+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:17:50.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:17:50.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:18:23.568+0000] {processor.py:186} INFO - Started process (PID=7043) to work on /opt/airflow/dags/test.py
[2024-10-26T18:18:23.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:18:23.571+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:18:23.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:18:23.582+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:18:23.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:18:23.584+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:18:23.602+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:18:56.302+0000] {processor.py:186} INFO - Started process (PID=7107) to work on /opt/airflow/dags/test.py
[2024-10-26T18:18:56.304+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:18:56.306+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:18:56.306+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:18:56.316+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:18:56.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:18:56.317+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:18:56.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:19:29.075+0000] {processor.py:186} INFO - Started process (PID=7171) to work on /opt/airflow/dags/test.py
[2024-10-26T18:19:29.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:19:29.079+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:19:29.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:19:29.091+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:19:29.088+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:19:29.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:19:29.108+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:20:02.103+0000] {processor.py:186} INFO - Started process (PID=7235) to work on /opt/airflow/dags/test.py
[2024-10-26T18:20:02.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:20:02.106+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:20:02.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:20:02.116+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:20:02.114+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:20:02.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:20:02.133+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:20:34.774+0000] {processor.py:186} INFO - Started process (PID=7299) to work on /opt/airflow/dags/test.py
[2024-10-26T18:20:34.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:20:34.778+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:20:34.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:20:34.790+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:20:34.785+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:20:34.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:20:34.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:21:07.327+0000] {processor.py:186} INFO - Started process (PID=7363) to work on /opt/airflow/dags/test.py
[2024-10-26T18:21:07.328+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:21:07.331+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:21:07.330+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:21:07.347+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:21:07.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:21:07.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:21:07.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.048 seconds
[2024-10-26T18:21:40.288+0000] {processor.py:186} INFO - Started process (PID=7427) to work on /opt/airflow/dags/test.py
[2024-10-26T18:21:40.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:21:40.291+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:21:40.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:21:40.302+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:21:40.300+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:21:40.304+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:21:40.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:22:13.271+0000] {processor.py:186} INFO - Started process (PID=7491) to work on /opt/airflow/dags/test.py
[2024-10-26T18:22:13.273+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:22:13.275+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:22:13.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:22:13.291+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:22:13.287+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:22:13.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:22:13.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-26T18:22:45.477+0000] {processor.py:186} INFO - Started process (PID=7555) to work on /opt/airflow/dags/test.py
[2024-10-26T18:22:45.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:22:45.480+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:22:45.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:22:45.491+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:22:45.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:22:45.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:22:45.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:23:18.399+0000] {processor.py:186} INFO - Started process (PID=7619) to work on /opt/airflow/dags/test.py
[2024-10-26T18:23:18.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:23:18.402+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:23:18.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:23:18.413+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:23:18.410+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:23:18.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:23:18.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:23:51.478+0000] {processor.py:186} INFO - Started process (PID=7683) to work on /opt/airflow/dags/test.py
[2024-10-26T18:23:51.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:23:51.480+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:23:51.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:23:51.492+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:23:51.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:23:51.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:23:51.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:24:23.419+0000] {processor.py:186} INFO - Started process (PID=7747) to work on /opt/airflow/dags/test.py
[2024-10-26T18:24:23.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:24:23.422+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:24:23.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:24:23.439+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:24:23.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:24:23.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:24:23.464+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.050 seconds
[2024-10-26T18:24:56.360+0000] {processor.py:186} INFO - Started process (PID=7811) to work on /opt/airflow/dags/test.py
[2024-10-26T18:24:56.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:24:56.363+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:24:56.363+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:24:56.375+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:24:56.372+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:24:56.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:24:56.392+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:25:29.425+0000] {processor.py:186} INFO - Started process (PID=7875) to work on /opt/airflow/dags/test.py
[2024-10-26T18:25:29.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:25:29.427+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:25:29.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:25:29.439+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:25:29.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:25:29.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:25:29.455+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:26:01.417+0000] {processor.py:186} INFO - Started process (PID=7939) to work on /opt/airflow/dags/test.py
[2024-10-26T18:26:01.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:26:01.420+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:26:01.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:26:01.434+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:26:01.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:26:01.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:26:01.461+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.049 seconds
[2024-10-26T18:26:34.706+0000] {processor.py:186} INFO - Started process (PID=8003) to work on /opt/airflow/dags/test.py
[2024-10-26T18:26:34.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:26:34.709+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:26:34.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:26:34.722+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:26:34.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:26:34.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:26:34.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:27:07.148+0000] {processor.py:186} INFO - Started process (PID=8067) to work on /opt/airflow/dags/test.py
[2024-10-26T18:27:07.149+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:27:07.151+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:27:07.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:27:07.162+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:27:07.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:27:07.163+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:27:07.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:27:40.128+0000] {processor.py:186} INFO - Started process (PID=8131) to work on /opt/airflow/dags/test.py
[2024-10-26T18:27:40.129+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:27:40.132+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:27:40.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:27:40.146+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:27:40.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:27:40.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:27:40.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.043 seconds
[2024-10-26T18:28:13.310+0000] {processor.py:186} INFO - Started process (PID=8195) to work on /opt/airflow/dags/test.py
[2024-10-26T18:28:13.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:28:13.313+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:28:13.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:28:13.324+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:28:13.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:28:13.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:28:13.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:28:45.321+0000] {processor.py:186} INFO - Started process (PID=8259) to work on /opt/airflow/dags/test.py
[2024-10-26T18:28:45.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:28:45.323+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:28:45.323+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:28:45.334+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:28:45.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:28:45.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:28:45.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-26T18:29:18.558+0000] {processor.py:186} INFO - Started process (PID=8323) to work on /opt/airflow/dags/test.py
[2024-10-26T18:29:18.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:29:18.562+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:29:18.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:29:18.577+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:29:18.573+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:29:18.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:29:18.609+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.060 seconds
[2024-10-26T18:29:50.668+0000] {processor.py:186} INFO - Started process (PID=8387) to work on /opt/airflow/dags/test.py
[2024-10-26T18:29:50.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:29:50.671+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:29:50.671+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:29:50.685+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:29:50.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:29:50.687+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:29:50.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.046 seconds
[2024-10-26T18:30:23.497+0000] {processor.py:186} INFO - Started process (PID=8451) to work on /opt/airflow/dags/test.py
[2024-10-26T18:30:23.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:30:23.501+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:30:23.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:30:23.515+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:30:23.512+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:30:23.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:30:23.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.043 seconds
[2024-10-26T18:30:56.424+0000] {processor.py:186} INFO - Started process (PID=8515) to work on /opt/airflow/dags/test.py
[2024-10-26T18:30:56.425+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:30:56.427+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:30:56.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:30:56.440+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:30:56.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:30:56.442+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:30:56.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:31:29.471+0000] {processor.py:186} INFO - Started process (PID=8579) to work on /opt/airflow/dags/test.py
[2024-10-26T18:31:29.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:31:29.475+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:31:29.475+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:31:29.490+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:31:29.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:31:29.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:31:29.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.051 seconds
[2024-10-26T18:32:01.818+0000] {processor.py:186} INFO - Started process (PID=8643) to work on /opt/airflow/dags/test.py
[2024-10-26T18:32:01.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:32:01.821+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:32:01.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:32:01.831+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:32:01.828+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:32:01.832+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:32:01.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-26T18:32:34.749+0000] {processor.py:186} INFO - Started process (PID=8707) to work on /opt/airflow/dags/test.py
[2024-10-26T18:32:34.750+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:32:34.752+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:32:34.752+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:32:34.766+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:32:34.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:32:34.767+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:32:34.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.042 seconds
[2024-10-26T18:33:07.379+0000] {processor.py:186} INFO - Started process (PID=8771) to work on /opt/airflow/dags/test.py
[2024-10-26T18:33:07.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:33:07.383+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:33:07.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:33:07.398+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:33:07.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:33:07.400+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:33:07.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.046 seconds
[2024-10-26T18:33:40.480+0000] {processor.py:186} INFO - Started process (PID=8835) to work on /opt/airflow/dags/test.py
[2024-10-26T18:33:40.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:33:40.483+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:33:40.483+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:33:40.495+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:33:40.492+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:33:40.496+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:33:40.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:34:13.276+0000] {processor.py:186} INFO - Started process (PID=8899) to work on /opt/airflow/dags/test.py
[2024-10-26T18:34:13.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:34:13.279+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:34:13.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:34:13.289+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:34:13.286+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:34:13.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:34:13.304+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-10-26T18:34:45.980+0000] {processor.py:186} INFO - Started process (PID=8963) to work on /opt/airflow/dags/test.py
[2024-10-26T18:34:45.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:34:45.983+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:34:45.983+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:34:45.994+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:34:45.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:34:45.995+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:34:46.010+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-26T18:35:17.870+0000] {processor.py:186} INFO - Started process (PID=9027) to work on /opt/airflow/dags/test.py
[2024-10-26T18:35:17.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:35:17.874+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:35:17.873+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:35:17.885+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:35:17.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:35:17.887+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:35:17.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:35:51.051+0000] {processor.py:186} INFO - Started process (PID=9091) to work on /opt/airflow/dags/test.py
[2024-10-26T18:35:51.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:35:51.056+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:35:51.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:35:51.069+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:35:51.066+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:35:51.071+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:35:51.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.057 seconds
[2024-10-26T18:36:24.103+0000] {processor.py:186} INFO - Started process (PID=9155) to work on /opt/airflow/dags/test.py
[2024-10-26T18:36:24.104+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:36:24.106+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:36:24.106+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:36:24.119+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:36:24.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:36:24.121+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:36:24.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:36:56.405+0000] {processor.py:186} INFO - Started process (PID=9219) to work on /opt/airflow/dags/test.py
[2024-10-26T18:36:56.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:36:56.408+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:36:56.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:36:56.419+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:36:56.416+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:36:56.420+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:36:56.436+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
[2024-10-26T18:37:29.136+0000] {processor.py:186} INFO - Started process (PID=9283) to work on /opt/airflow/dags/test.py
[2024-10-26T18:37:29.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:37:29.139+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:37:29.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:37:29.150+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:37:29.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:37:29.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:37:29.165+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.034 seconds
[2024-10-26T18:38:01.896+0000] {processor.py:186} INFO - Started process (PID=9347) to work on /opt/airflow/dags/test.py
[2024-10-26T18:38:01.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:38:01.899+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:38:01.899+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:38:01.910+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:38:01.907+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:38:01.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:38:01.929+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:38:34.684+0000] {processor.py:186} INFO - Started process (PID=9411) to work on /opt/airflow/dags/test.py
[2024-10-26T18:38:34.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:38:34.687+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:38:34.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:38:34.698+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:38:34.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:38:34.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:38:34.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.036 seconds
[2024-10-26T18:39:07.585+0000] {processor.py:186} INFO - Started process (PID=9475) to work on /opt/airflow/dags/test.py
[2024-10-26T18:39:07.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:39:07.588+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:39:07.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:39:07.601+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:39:07.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:39:07.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:39:07.618+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:39:40.704+0000] {processor.py:186} INFO - Started process (PID=9539) to work on /opt/airflow/dags/test.py
[2024-10-26T18:39:40.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:39:40.709+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:39:40.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:39:40.725+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:39:40.722+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:39:40.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:39:40.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.051 seconds
[2024-10-26T18:40:12.475+0000] {processor.py:186} INFO - Started process (PID=9603) to work on /opt/airflow/dags/test.py
[2024-10-26T18:40:12.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:40:12.479+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:40:12.478+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:40:12.495+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:40:12.491+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:40:12.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:40:12.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.046 seconds
[2024-10-26T18:40:46.050+0000] {processor.py:186} INFO - Started process (PID=9667) to work on /opt/airflow/dags/test.py
[2024-10-26T18:40:46.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:40:46.054+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:40:46.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:40:46.065+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:40:46.062+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:40:46.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:40:46.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:41:18.832+0000] {processor.py:186} INFO - Started process (PID=9731) to work on /opt/airflow/dags/test.py
[2024-10-26T18:41:18.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:41:18.836+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:41:18.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:41:18.849+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:41:18.845+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:41:18.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:41:18.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:41:50.656+0000] {processor.py:186} INFO - Started process (PID=9795) to work on /opt/airflow/dags/test.py
[2024-10-26T18:41:50.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:41:50.659+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:41:50.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:41:50.669+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:41:50.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:41:50.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:41:50.689+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:42:23.416+0000] {processor.py:186} INFO - Started process (PID=9859) to work on /opt/airflow/dags/test.py
[2024-10-26T18:42:23.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:42:23.419+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:42:23.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:42:23.432+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:42:23.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:42:23.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:42:23.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.043 seconds
[2024-10-26T18:42:56.370+0000] {processor.py:186} INFO - Started process (PID=9923) to work on /opt/airflow/dags/test.py
[2024-10-26T18:42:56.371+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:42:56.373+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:42:56.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:42:56.385+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:42:56.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:42:56.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:42:56.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.041 seconds
[2024-10-26T18:43:29.683+0000] {processor.py:186} INFO - Started process (PID=9987) to work on /opt/airflow/dags/test.py
[2024-10-26T18:43:29.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:43:29.686+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:43:29.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:43:29.697+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:43:29.695+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:43:29.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:43:29.716+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.038 seconds
[2024-10-26T18:44:01.864+0000] {processor.py:186} INFO - Started process (PID=10051) to work on /opt/airflow/dags/test.py
[2024-10-26T18:44:01.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:44:01.867+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:44:01.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:44:01.879+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:44:01.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:44:01.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:44:01.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.037 seconds
[2024-10-26T18:44:34.636+0000] {processor.py:186} INFO - Started process (PID=10115) to work on /opt/airflow/dags/test.py
[2024-10-26T18:44:34.637+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:44:34.639+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:44:34.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:44:34.652+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:44:34.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:44:34.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:44:34.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.040 seconds
[2024-10-26T18:45:07.623+0000] {processor.py:186} INFO - Started process (PID=10179) to work on /opt/airflow/dags/test.py
[2024-10-26T18:45:07.624+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:45:07.627+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:45:07.626+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:45:07.639+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:45:07.636+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:45:07.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:45:07.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.045 seconds
[2024-10-26T18:45:40.706+0000] {processor.py:186} INFO - Started process (PID=10243) to work on /opt/airflow/dags/test.py
[2024-10-26T18:45:40.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2024-10-26T18:45:40.709+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:45:40.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2024-10-26T18:45:40.720+0000] {logging_mixin.py:190} INFO - [2024-10-26T18:45:40.717+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
[2024-10-26T18:45:40.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/test.py
[2024-10-26T18:45:40.736+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.035 seconds
